FROM node:latest

# Create app directory
RUN mkdir -p /usr/src/app

RUN npm install nodemon -g

WORKDIR /usr/src/app

COPY package.json /app/package.json

RUN cd /app; npm install; npm cache clean

COPY . /app

WORKDIR /app

EXPOSE 3000

#CMD ["npm", "run", "start-dev"]